[workspace]
resolver = "2"
members = [
    "crates/operator"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
kube = { version = "0.99.0", features = ["runtime", "derive", "client", "ws"] }
k8s-openapi = { version = "0.24.0", features = ["v1_30", "schemars"] }
schemars = { version = "0.8.12", features = ["chrono"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version =  "0.1.17", features = ["sync"] }
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
anyhow = "1.0"
async-trait = "0.1"
uuid = { version = "1.6", features = ["v4", "serde"] }
testcontainers = { version = "0.23.3" }
testcontainers-modules = { version = "0.11.6", features = ["k3s"] }
http = "0.2"
rand = "0.9.1"
assert-json-diff = "2.0.2"
structopt = "0.3.26"
pretty_assertions = { version = "1.4.1", default-features = false, features = ["alloc"] }
axum = "0.8.3"
reqwest = "0.12.15"
rmcp = { version = "0.1.5", features = ["client", "server"] }
unmcp-resources = { path = "crates/resources" }
unmcp-test-utils = { path = "crates/test-utils" }
