[package]
name = "unmcp"
version = "0.1.0"
edition = "2021"
description = "Unified MCP operator for Kubernetes"
license = "MIT"

[dependencies]
kube = { version = "0.87.1", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.20.0", features = ["v1_27"] }
schemars = { version = "0.8.12", features = ["chrono"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
anyhow = "1.0"
async-trait = "0.1"
uuid = { version = "1.6", features = ["v4", "serde"] }
testcontainers = { version = "0.23.3" }
testcontainers-modules = { version = "0.11.6", features = ["k3s"] }
http = "0.2"
rand = "0.9.1"
assert-json-diff = "2.0.2"
structopt = "0.3.26"
pretty_assertions = { version = "1.4.1", default-features = false, features = ["alloc"] }

[lib]
name = "unmcp"
path = "./src/lib.rs"

[[bin]]
name = "unmcp"
path = "./src/main.rs"
