apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmcp-operator
  labels:
    app: nmcp-operator
spec:
  # We will manually scale this deployment to 1 when we need to test the gateway.
  replicas: 0
  selector:
    matchLabels:
      app: nmcp-operator
  template:
    metadata:
      labels:
        app: nmcp-operator
    spec:
      serviceAccountName: nmcp-controller
      containers:
      - name: nmcp
        image: ghcr.io/nwrx/nmcp:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        args:
          - operator
          - --kubeconfig=""