apiVersion: v1
kind: Service
metadata:
  name: nmcp-gateway-service
  namespace: default
  labels:
    app: nmcp-gateway
  annotations:
    # Specific annotation for k3s/traefik to expose the service externally
    traefik.ingress.kubernetes.io/service.serverstransport: "default@internal"
spec:
  selector:
    app: nmcp-gateway
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  type: NodePort